language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.4"
  - "2.2.0"
env:
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.14"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.9"
  - "RAILS_VERSION=4.2.0"

addons:
  code_climate:
    repo_token: 970a221275a9af67dcd65c19f074b8f5e94581c97ab883ad6a974dd4b425b3bc
